apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-example-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-example-docker
      tier: web-app
  template:
    metadata:
      labels:
        app: go-example-docker
        tier: web-app
    spec:
      containers:
      # To use local docker images, see link blog :
        - name: go-example-docker
          image: example-docker-img:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128M"
              cpu: "500m"
          ports:
            - containerPort: 8080
              protocol: TCP

