apiVersion: v1
kind: Service
metadata:
  name: go-example-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: go-example-docker
    tier: web-app
  ports:
    - port: 30000
      protocol: TCP
      targetPort: 8080
